### ISSUE TITLE
spelling in variable name

### ISSUE THREAD

**Issue by JanderHungrige** [NXPmicro/pyarmnn-release#6]
Hi,
when describing how to use the ArmNN for inference, I think you misspelled the variable `output_binding_info` in the next line `outputs_binding_info`. One 's' to much.
Cheers

```
...
# Get output binding information for an output layer by using the layer name.
output_binding_info = parser.GetNetworkOutputBindingInfo(0, 'model/output')
output_tensors = ann.make_output_tensors([outputs_binding_info])
```

**Comment by pavel-macenauer-nxp** [comment]
@JanderHungrige Thx for letting us know. We will fix it with the next release.
